---
- hosts: all
  name: Arch GNOME Playbook
  pre_tasks:
    - name: System details
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items: 
      - "{{ ansible_distribution }}"
      - "{{ ansible_distribution_release }}"
      - "{{ ansible_distribution_version }}"
      - "{{ ansible_distribution_major_version }}"
    - name: Update repositories
      become: yes
      community.general.pacman:
        update_cache: True
      changed_when: False
  tasks:
    - include: tasks/aur-user.yml
    - include: tasks/pacman.yml
    - include: tasks/git.yml
    - include: tasks/yay.yml 
    - include: tasks/pacman-aur.yml
    - include: tasks/update-grub.yml
    - include: tasks/main-packages.yml
    - include: tasks/firewall.yml
    - include: tasks/printing.yml
    - name: Install GNOME
      ansible.builtin.include_role:
        name: lorenzobettini.my_gnome_role
    #- include: tasks/gnome-packages.yml
    #- include: tasks/gnome-tracker.yml
    #- include: tasks/gnome-arch-extensions.yml
    #- include: tasks/gnome-configurations.yml
    #- include: tasks/gnome-templates.yml
    #- include: tasks/flatpak.yml
    #- include: tasks/gnome-extension-manager.yml
    #- include: tasks/guake.yml
    - name: Install Oh My Zsh
      ansible.builtin.include_role:
        name: lorenzobettini.oh_my_zsh
    #- include: tasks/zsh.yml
    #- include: tasks/zsh-antigen.yml
    - include: tasks/zsh-gnome.yml
    - include: tasks/java-packages.yml
    - include: tasks/google-chrome.yml
    - include: tasks/dropbox.yml
    # Temporarily disabled
    # see https://github.com/LorenzoBettini/ansible-arch-playbooks/issues/11
    # - include: tasks/dropbox-nautilus.yml
    - include: tasks/docker.yml
    - include: tasks/cronie.yml
    - include: tasks/recoll.yml
    - include: tasks/visual-studio-code.yml
    - include: tasks/libreoffice.yml
    - include: tasks/other-packages.yml
    - include: tasks/skype.yml
    - include: tasks/patch-xdg-autostart.yml
    - tags: latex
      block:
      - include: tasks/latex.yml
