---
- hosts: all
  pre_tasks:
    - name: System details
      ansible.builtin.debug: msg="{{ item }}"
      with_items: 
      - "{{ ansible_distribution }}"
      - "{{ ansible_distribution_release }}"
      - "{{ ansible_distribution_version }}"
      - "{{ ansible_distribution_major_version }}"
    - name: update repositories
      become: yes
      community.general.pacman: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/aur-user.yml
    - include: tasks/git.yml
    - include: tasks/yay.yml 
    - include: tasks/update-grub.yml
    - include: tasks/main-packages.yml
    - include: tasks/gnome-packages.yml
    - include: tasks/gnome-arch-extensions.yml
    - include: tasks/gnome-configurations.yml
    - include: tasks/gnome-templates.yml
    - include: tasks/gnome-tracker.yml
    - include: tasks/flatpak.yml
    - include: tasks/gnome-extension-manager.yml
    - include: tasks/guake.yml
    - include: tasks/zsh.yml
    - include: tasks/zsh-antigen.yml
    - include: tasks/java-packages.yml
    - include: tasks/google-chrome.yml
    - include: tasks/dropbox.yml
    - include: tasks/docker.yml
    - include: tasks/vscode.yml
    - include: tasks/libreoffice.yml
    - include: tasks/other-packages.yml
