---
- hosts: all
  pre_tasks:
    - name: System details
      debug: msg="{{ item }}"
      with_items: 
      - "{{ ansible_distribution }}"
      - "{{ ansible_distribution_release }}"
      - "{{ ansible_distribution_version }}"
      - "{{ ansible_distribution_major_version }}"
    - name: update repositories
      become: yes
      pacman: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/aur-user.yml
    - include: tasks/git.yml
    - include: tasks/yay.yml 
    - include: tasks/update-grub.yml

