---
- hosts: all
  name: Arch Hyprland Playbook
  pre_tasks:
    - name: System details
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items: 
      - "{{ ansible_distribution }}"
      - "{{ ansible_distribution_release }}"
      - "{{ ansible_distribution_version }}"
      - "{{ ansible_distribution_major_version }}"
    - name: Update repositories
      become: true
      community.general.pacman:
        update_cache: True
      changed_when: False
  tasks:
    - include_tasks: tasks/aur-user.yml
    - include_tasks: tasks/pacman.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/yay.yml 
    - include_tasks: tasks/pacman-aur.yml
    - include_tasks: tasks/update-grub.yml
    - include_tasks: tasks/main-packages.yml
    - include_tasks: tasks/hyprland-packages.yml
    - include_tasks: tasks/kde-packages.yml
    - include_tasks: tasks/tlp.yml
    - include_tasks: tasks/firewall.yml
    - include_tasks: tasks/printing.yml
    - include_tasks: tasks/flatpak.yml
    - name: Install Oh My Zsh
      ansible.builtin.include_role:
        name: lorenzobettini.oh_my_zsh
      vars:
        with_starship: false
        copy_dot_files: false
    - tags: java
      block:
      - include_tasks: tasks/java-packages.yml
    - include_tasks: tasks/google-chrome.yml
    - tags: dropbox
      block:
      - include_tasks: tasks/dropbox.yml
    - tags: docker
      block:
      - include_tasks: tasks/docker.yml
    - include_tasks: tasks/cronie.yml
    - include_tasks: tasks/recoll.yml
    - include_tasks: tasks/vscode.yml
    - include_tasks: tasks/libreoffice.yml
    - include_tasks: tasks/other-packages.yml
    - tags: skype
      block:
      - include_tasks: tasks/skype.yml
