---
- hosts: all
  name: Arch GNOME Playbook
  pre_tasks:
    - name: System details
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items: 
      - "{{ ansible_distribution }}"
      - "{{ ansible_distribution_release }}"
      - "{{ ansible_distribution_version }}"
      - "{{ ansible_distribution_major_version }}"
    - name: Update repositories
      become: true
      community.general.pacman:
        update_cache: True
      changed_when: False
  tasks:
    - tags: aur
      block:
      - include_tasks: tasks/aur-user.yml
    - include_tasks: tasks/pacman.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/yay.yml 
    - include_tasks: tasks/pacman-aur.yml
    - include_tasks: tasks/update-grub.yml
    - include_tasks: tasks/main-packages.yml
    - include_tasks: tasks/power-profiles.yml
    - include_tasks: tasks/firewall.yml
    - include_tasks: tasks/printing.yml
    - name: Install GNOME
      ansible.builtin.include_role:
        name: lorenzobettini.my_gnome_role
      vars:
        modify_dconf: false
    - include_tasks: tasks/gnome-additional-packages.yml
    #- include_tasks: tasks/gnome-tracker.yml
    #- include_tasks: tasks/gnome-arch-extensions.yml
    #- include_tasks: tasks/gnome-configurations.yml
    #- include_tasks: tasks/gnome-templates.yml
    #- include_tasks: tasks/flatpak.yml
    #- include_tasks: tasks/gnome-extension-manager.yml
    #- include_tasks: tasks/guake.yml
    - name: Install Oh My Zsh
      ansible.builtin.include_role:
        name: lorenzobettini.oh_my_zsh
      vars:
        with_starship: false
        copy_dot_files: false
    #- include_tasks: tasks/zsh.yml
    #- include_tasks: tasks/zsh-antigen.yml
    # - include_tasks: tasks/zsh-gnome.yml
    - block:
      - include_tasks: tasks/java-packages.yml
      tags: java
    - include_tasks: tasks/google-chrome.yml
    - include_tasks: tasks/dropbox.yml
    #- include_tasks: tasks/dropbox-nautilus.yml
    - tags: docker
      block:
      - include_tasks: tasks/docker.yml
    - include_tasks: tasks/cronie.yml
    - include_tasks: tasks/recoll.yml
    - include_tasks: tasks/visual-studio-code.yml
    - include_tasks: tasks/libreoffice.yml
    - include_tasks: tasks/other-packages.yml
    - tags: skype
      block:
      - include_tasks: tasks/skype.yml
    - include_tasks: tasks/patch-xdg-autostart.yml
    - tags: latex
      block:
      - include_tasks: tasks/latex.yml
