---
- hosts: all
  name: Arch ARM GNOME Playbook
  pre_tasks:
    - name: System details
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items: 
      - "{{ ansible_distribution }}"
      - "{{ ansible_distribution_release }}"
      - "{{ ansible_distribution_version }}"
      - "{{ ansible_distribution_major_version }}"
      - "{{ ansible_architecture }}"
    - name: Update repositories
      become: True
      community.general.pacman:
        update_cache: True
      changed_when: False
  tasks:
    - include: tasks/aur-user.yml
    - include: tasks/pacman.yml
    - include: tasks/git.yml
    - include: tasks/yay.yml 
    - include: tasks/pacman-aur.yml
    - include: tasks/main-packages.yml
    - name: Install GNOME
      ansible.builtin.include_role:
        name: lorenzobettini.my_gnome_role
      vars:
        with_flatpak: false
    - name: Install Oh My Zsh
      ansible.builtin.include_role:
        name: lorenzobettini.oh_my_zsh
    - include: tasks/zsh-gnome.yml
    - include: tasks/java-latest-lts.yml
    - include: tasks/visual-studio-code.yml
    - include: tasks/libreoffice.yml
    - include: tasks/other-packages.yml
