---
roles:
  # Install a role from Ansible Galaxy.
  - name: gantsign.maven
  - name: petermosmans.customize-gnome

collections:
  # Install a collection from Ansible Galaxy.
  - name: kewlfft.aur
  - name: community.general
