# Task to install additional fonts
- name: Install Additional Fonts
  become: true
  community.general.pacman:
    state: present
    name:
      - ttf-fira-mono
      - otf-firamono-nerd
      - ttf-jetbrains-mono
      - ttf-jetbrains-mono-nerd
      - ttf-meslo-nerd
      - ttf-hack-nerd
      - ttf-cascadia-mono-nerd
      - ttf-iosevkaterm-nerd
      - ttc-iosevka
