- name: Install Gnome Packages
  become: yes
  community.general.pacman:
    state: present
    name:
    - gnome-shell
    - gnome-tweaks
    - dconf-editor
    - python-psutil
    - xdg-utils # required for xdg-mime below
    - gnome-screenshot # the original screenshot application
    - baobab
    - deja-dup
    - eog
    - evince
    - evolution
    - file-roller
    - gnome-backgrounds
    - gnome-calculator
    - gnome-calendar
    - gnome-contacts
    - gnome-logs
    - gnome-photos
    - gnome-remote-desktop
    - gnome-system-monitor
    - gnome-weather
    - simple-scan
    - gvfs
    - gvfs-afc
    - gvfs-goa
    - gvfs-google
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-nfs
    - gvfs-smb

- name: Gnome Shell version
  ansible.builtin.command: "gnome-shell --version"
  changed_when: False
  register: command_output

- name: Gnome Shell version show
  ansible.builtin.debug:
    var: command_output.stdout

- name: Install Gnome Packages from AUR
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
    - gnome-text-editor
    - gnome-browser-connector # replaces chrome-gnome-shell

- name: Ensure xdg mime default for text files application is set
  ansible.builtin.command: "xdg-mime default {{ item[0].desktop_file }} {{ item[1] }}"
  changed_when: False
  with_subelements:
    - "{{ xdg_mime_defaults }}"
    - mime_types
  vars:
    xdg_mime_defaults:
    - desktop_file: org.gnome.TextEditor.desktop
      mime_types:
      - text/plain
      - text/xml

- name: Uninstall Gnome terminal...
  become: yes
  community.general.pacman:
    state: absent
    name:
    - gnome-terminal

- name: .. and install Gnome terminal with transparency
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
    - gnome-terminal-transparency
