- name: Install Hyprland Packages
  become: True
  community.general.pacman:
    state: present
    name:
    - hyprland
    - polkit-kde-agent
    - grim
    - wl-clipboard
    - slurp
    - swaybg
    - brightnessctl
    - swayidle
    - swaylock
    - xdg-desktop-portal-hyprland
    - otf-font-awesome
    - wmctrl
    - network-manager-applet
    - mako

- name: Install Additional AUR packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
    - wlogout

- name: Install Terminals
  become: true
  community.general.pacman:
    state: present
    name:
    - kitty
    - alacritty

- name: Install Nemo
  become: true
  community.general.pacman:
    state: present
    name:
    - nemo
    - python-psutil # Actually required by the following dconf task

- name: Set kitty as Nemo terminal
  community.general.dconf:
    key: "/org/cinnamon/desktop/applications/terminal/exec"
    value: "'kitty'"

- name: Install Waybar
  become: true
  community.general.pacman:
    state: present
    name:
    - waybar

#- name: Install Waybar
#  become: true
#  become_user: aur_builder
#  kewlfft.aur.aur:
#    state: present
#    name:
#    - waybar-hyprland-git

- name: Install Rofi
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
    - rofi-lbonn-wayland-git
