- name: Install Kde Packages
  become: yes
  community.general.pacman:
    state: present
    name:
    - kate
    - spectacle
    - ark
    - konsole
    - dolphin
    - okular
    - gwenview
    - yakuake
    - korganizer
    - kaddressbook
    - kdepim-addons
    - kio-gdrive
    - dolphin-plugins
    - plasma-systemmonitor
    - kdeplasma-addons
    - kcalc
    - plasma-workspace-wallpapers
    - kvantum
#    - latte-dock # it's not maintained anymore
