# - name: Install Zathura PDF reader
#   become: true
#   community.general.pacman:
#     state: present
#     name:
#       - zathura-pdf-poppler

- name: Install Sioyek requirements
  become: true
  ansible.builtin.package:
    state: present
    name:
      - tesseract-data-ita
      - tesseract-data-eng

- name: Install Sioyek
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name: sioyek

- name: Install Latex Packages
  become: true
  community.general.pacman:
    state: present
    name:
      - texlive-core
      - texlive-latexextra
      - texlive-plaingeneric
      - texlive-bibtexextra
      - texlive-fontsextra
      - texlive-science
      - texlive-pictures
      - texlive-langitalian # for curriculum
      - texlive-fontutils # for repstopdf (convert eps to pdf)
      - texlive-binextra # for latexmk (used by vimtex)
