- name: Uninstall mlocate and exfat-utils
  become: yes
  community.general.pacman:
    state: absent
    name:
    - mlocate
    - exfat-utils

- name: Install Other Packages
  become: yes
  community.general.pacman:
    state: present
    name:
    - emacs
    - homebank
    - vlc
    - aribb24 # for MPEG
    - meld
    - iotop
    - lsof
    - nethogs
    - unrar
    - hyphen-it
    - hunspell-it
    - exfatprogs
    - ispell
    - gimp
    - tree
    - plocate
    - duf
    - noto-fonts
    - libappindicator-gtk3 # for Variety in Wayland
    - variety
    - powertop
    - usbutils # for lsusb
    - man-db # for man command

- name: Enable plocate-updatedb.timer
  become: yes
  ansible.builtin.systemd:
    name: plocate-updatedb.timer
    enabled: yes

# When using BTRFS remember to
#    edit the file /etc/updatedb.conf
#    replace PRUNE_BIND_MOUNTS = “yes” with PRUNE_BIND_MOUNTS = “no”
#    save, exit and re-run updatedb

- name: Install other AUR packages
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
    - inxi
