- name: Uninstall exfat-utils
  become: true
  community.general.pacman:
    state: absent
    name:
      - exfat-utils

- name: Install Other Packages
  become: true
  community.general.pacman:
    state: present
    name:
      - emacs
      - homebank
      - vlc
      - vlc-plugins-all
      - aribb24 # for MPEG
      - meld
      - iotop
      - lsof
      - nethogs
      - unrar
      - hyphen-it
      - hunspell-it
      - exfatprogs
      - ispell
      - gimp
      - tree
      - plocate
      - duf
      - noto-fonts
      - libappindicator-gtk3 # for Variety in Wayland
      - variety
      - powertop
      - usbutils # for lsusb
      - man-db # for man command

- name: Install Neovim and requirements
  become: true
  community.general.pacman:
    state: present
    name:
      - neovim
      - npm # required for some neovim LSPs, e.g., bashls
      - wl-clipboard # for neovim clipboard sharing in Wayland
      - xclip # for neovim clipboard sharing in X11
      - lazygit
      - git-delta
      - tree-sitter-cli # required for the "latex" grammar

# shellcheck is NOT available as standard package for arm
- name: Install shellcheck
  become: true
  community.general.pacman:
    state: present
    name:
      - shellcheck # required for neovim LSP bashls
  when: ansible_architecture != "aarch64"

# shellcheck is available in AUR for arm
- name: Install shellcheck from AUR
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
      - shellcheck-bin # required for neovim LSP bashls
  when: ansible_architecture == "aarch64"

- name: Install Terminals
  become: true
  community.general.pacman:
    state: present
    name:
      - kitty
      - alacritty

- name: Enable plocate-updatedb.timer
  become: true
  ansible.builtin.systemd:
    name: plocate-updatedb.timer
    enabled: yes

# When using BTRFS remember to
#    edit the file /etc/updatedb.conf
#    replace PRUNE_BIND_MOUNTS = “yes” with PRUNE_BIND_MOUNTS = “no”
#    save, exit and re-run updatedb

- name: Install other AUR packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
      - inxi

- name: Install Chezmoi
  become: true
  community.general.pacman:
    state: present
    name:
      - chezmoi

- name: Install chezmoi_modify_manager aarch64
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/VorpalBlade/chezmoi_modify_manager/releases/download/v3.3.0/chezmoi_modify_manager-v3.3.0-aarch64-unknown-linux-gnu.tar.gz"
    dest: /usr/local/bin
    remote_src: true
  when: ansible_architecture == "aarch64"

- name: Install chezmoi_modify_manager x86_64
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/VorpalBlade/chezmoi_modify_manager/releases/download/v3.3.0/chezmoi_modify_manager-v3.3.0-x86_64-unknown-linux-gnu.tar.gz"
    dest: /usr/local/bin
    remote_src: true
  when: ansible_architecture != "aarch64"
