- name: Install pacseek
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
    - pacseek-bin

- name: Install downgrade
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
    - downgrade
