- name: Install Printing packages
  become: true
  community.general.pacman:
    state: present
    name:
    - cups
    - cups-filters
    - cups-pdf
    - cups-pk-helper
    - libcups
    - splix
    - system-config-printer
    - avahi
    - nss-mdns # host name resolution via mDNS

- name: Enable service CUPS
  become: true
  ansible.builtin.systemd:
    name: cups
    enabled: yes
    state: started

- name: Enable service Avahi
  become: true
  ansible.builtin.systemd:
    name: avahi-daemon
    enabled: yes
    state: started

- name: Install Printing drivers
  become: true
  community.general.pacman:
    state: present
    name:
    - foomatic-db
    - foomatic-db-engine
    - foomatic-db-gutenprint-ppds
    - foomatic-db-nonfree
    - foomatic-db-nonfree-ppds
    - foomatic-db-ppds
    - hplip
    - gutenprint

- name: Enable network printer discovery
  become: true
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^hosts: '
    line: 'hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns'
    mode: 0644
