- name: Ensure old version of Skype is not installed
  become: true
  ansible.builtin.package:
    state: absent
    name:
    - skypeforlinux-stable-bin

- name: Install Skype
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
    - skypeforlinux-bin
