- name: Ensures power-profiles-deamon is not installed
  become: True
  community.general.pacman:
    state: absent
    name:
    - power-profiles-daemon

- name: Install TLP
  become: True
  community.general.pacman:
    state: present
    name:
    - tlp
    - tlp-rdw

- name: Enable TLP on boot
  become: True
  ansible.builtin.systemd:
    name: tlp.service
    enabled: yes

- name: Enable NetworkManager-dispatcher.service on boot
  become: True
  ansible.builtin.systemd:
    name: NetworkManager-dispatcher.service
    enabled: yes

- name: Disable systemd-rfkill.service
  become: True
  ansible.builtin.systemd:
    name: systemd-rfkill.service
    enabled: no

- name: Mask systemd-rfkill.service
  become: True
  ansible.builtin.systemd:
    name: systemd-rfkill.service
    masked: yes

- name: Disable systemd-rfkill.socket
  become: True
  ansible.builtin.systemd:
    name: systemd-rfkill.socket
    enabled: no

- name: Mask systemd-rfkill.socket
  become: True
  ansible.builtin.systemd:
    name: systemd-rfkill.socket
    masked: yes
