- name: Install Touchegg from AUR
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
    - touchegg

- name: Enable Touchegg on boot
  become: true
  ansible.builtin.service:
    name: touchegg
    enabled: yes