- name: Ensure fakeroot is installed
  become: True
  community.general.pacman:
    state: present
    name:
    - fakeroot

- name: Ensure base-devel is installed
  become: True
  community.general.pacman:
    state: present
    name:
    - base-devel
    - patch # needed for some AUR packages with patches to apply

- name: Install yay
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: yay
    use: makepkg
