- name: Ensure fakeroot is installed
  become: yes
  community.general.pacman:
    state: present
    name:
    - fakeroot

- name: Ensure base-devel is installed
  become: yes
  community.general.pacman:
    state: present
    name:
    - base-devel

- name: Install yay
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: yay
    use: makepkg
