---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: arch-instance
    image: arch-ansible
    platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
    dockerfile: ../docker/Dockerfile
    build_image: true
    command: ""
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../${MOLECULE_DISTRO:-arch-gnome}/converge.yml
verifier:
  name: ansible
