---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: "custom-arch-gnome-ansible"
    dockerfile: ../docker/Dockerfile
    command: ""
    privileged: true
    build_image: true
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../${MOLECULE_DISTRO:-arch-gnome}/converge.yml
verifier:
  name: ansible
