---
name: Molecule CI
on:
  push:
    paths-ignore:
     - '**.md'
  pull_request:
    paths-ignore:
     - '**.md'
  schedule:
    - cron: "0 7 * * 0"

jobs:

  cache-dependencies:
    name: Cache dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Cache pip installed packages.
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/Python/*
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install test dependencies.
        run: pip install -r pip/requirements.txt

      - name: Cache Ansible dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.ansible
            ~/.cache/ansible-*
          key: ${{ runner.os }}-ansible-pip-molecule-${{ hashFiles('requirements.yml') }}
          # restore-keys: ${{ runner.os }}-ansible-
          # make sure that when an exact cache is not found we start with new
          # downloaded requirements

      - name: Run Molecule dependency.
        run: molecule dependency
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

  test:
    needs: cache-dependencies
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        playbookdistro:
          - arch-gnome
          - arch-kde

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Cache Ansible dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.ansible
            ~/.cache/ansible-*
          key: ${{ runner.os }}-ansible-pip-molecule-${{ hashFiles('requirements.yml') }}
          # restore-keys: ${{ runner.os }}-ansible-
          # make sure that when an exact cache is not found we start with new
          # downloaded requirements

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Restore pip installed packages.
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/Python/*
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          # perfect cache key match

      - name: Show versions.
        run: molecule --version

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.playbookdistro }}
